/* This file was generated by SableCC (http://www.sablecc.org/). */

package grammar.ini.node;

import grammar.ini.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyReturn extends PReturn
{

    public AEmptyReturn()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyReturn();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyReturn(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
