/* This file was generated by SableCC (http://www.sablecc.org/). */

package grammar.ini.node;

import grammar.ini.analysis.*;

@SuppressWarnings("nls")
public final class AEventdclStmt extends PStmt
{
    private PPdcl _pdcl_;

    public AEventdclStmt()
    {
        // Constructor
    }

    public AEventdclStmt(
        @SuppressWarnings("hiding") PPdcl _pdcl_)
    {
        // Constructor
        setPdcl(_pdcl_);

    }

    @Override
    public Object clone()
    {
        return new AEventdclStmt(
            cloneNode(this._pdcl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEventdclStmt(this);
    }

    public PPdcl getPdcl()
    {
        return this._pdcl_;
    }

    public void setPdcl(PPdcl node)
    {
        if(this._pdcl_ != null)
        {
            this._pdcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pdcl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pdcl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pdcl_ == child)
        {
            this._pdcl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pdcl_ == oldChild)
        {
            setPdcl((PPdcl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
