/* This file was generated by SableCC (http://www.sablecc.org/). */

package grammar.ini.node;

import java.util.*;
import grammar.ini.analysis.*;

@SuppressWarnings("nls")
public final class AFordownLoop extends PLoop
{
    private TId _id_;
    private PVal _start_;
    private PVal _finish_;
    private final LinkedList<PStmt> _stmt_ = new LinkedList<PStmt>();

    public AFordownLoop()
    {
        // Constructor
    }

    public AFordownLoop(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PVal _start_,
        @SuppressWarnings("hiding") PVal _finish_,
        @SuppressWarnings("hiding") List<?> _stmt_)
    {
        // Constructor
        setId(_id_);

        setStart(_start_);

        setFinish(_finish_);

        setStmt(_stmt_);

    }

    @Override
    public Object clone()
    {
        return new AFordownLoop(
            cloneNode(this._id_),
            cloneNode(this._start_),
            cloneNode(this._finish_),
            cloneList(this._stmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFordownLoop(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PVal getStart()
    {
        return this._start_;
    }

    public void setStart(PVal node)
    {
        if(this._start_ != null)
        {
            this._start_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._start_ = node;
    }

    public PVal getFinish()
    {
        return this._finish_;
    }

    public void setFinish(PVal node)
    {
        if(this._finish_ != null)
        {
            this._finish_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._finish_ = node;
    }

    public LinkedList<PStmt> getStmt()
    {
        return this._stmt_;
    }

    public void setStmt(List<?> list)
    {
        for(PStmt e : this._stmt_)
        {
            e.parent(null);
        }
        this._stmt_.clear();

        for(Object obj_e : list)
        {
            PStmt e = (PStmt) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._stmt_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._start_)
            + toString(this._finish_)
            + toString(this._stmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._start_ == child)
        {
            this._start_ = null;
            return;
        }

        if(this._finish_ == child)
        {
            this._finish_ = null;
            return;
        }

        if(this._stmt_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._start_ == oldChild)
        {
            setStart((PVal) newChild);
            return;
        }

        if(this._finish_ == oldChild)
        {
            setFinish((PVal) newChild);
            return;
        }

        for(ListIterator<PStmt> i = this._stmt_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStmt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
