/* This file was generated by SableCC (http://www.sablecc.org/). */

package grammar.ini.node;

import grammar.ini.analysis.*;

@SuppressWarnings("nls")
public final class AIfstmtStmt extends PStmt
{
    private PIfstmt _ifstmt_;

    public AIfstmtStmt()
    {
        // Constructor
    }

    public AIfstmtStmt(
        @SuppressWarnings("hiding") PIfstmt _ifstmt_)
    {
        // Constructor
        setIfstmt(_ifstmt_);

    }

    @Override
    public Object clone()
    {
        return new AIfstmtStmt(
            cloneNode(this._ifstmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfstmtStmt(this);
    }

    public PIfstmt getIfstmt()
    {
        return this._ifstmt_;
    }

    public void setIfstmt(PIfstmt node)
    {
        if(this._ifstmt_ != null)
        {
            this._ifstmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifstmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifstmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifstmt_ == child)
        {
            this._ifstmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifstmt_ == oldChild)
        {
            setIfstmt((PIfstmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
