/* This file was generated by SableCC (http://www.sablecc.org/). */

package grammar.ini.node;

import grammar.ini.analysis.*;

@SuppressWarnings("nls")
public final class TDownto extends Token
{
    public TDownto()
    {
        super.setText("downto");
    }

    public TDownto(int line, int pos)
    {
        super.setText("downto");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDownto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDownto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDownto text.");
    }
}
