/* This file was generated by SableCC (http://www.sablecc.org/). */

package grammar.ini.node;

import grammar.ini.analysis.*;

@SuppressWarnings("nls")
public final class TMain extends Token
{
    public TMain()
    {
        super.setText("Main");
    }

    public TMain(int line, int pos)
    {
        super.setText("Main");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMain(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMain(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMain text.");
    }
}
