/* This file was generated by SableCC (http://www.sablecc.org/). */

package grammar.ini.node;

import grammar.ini.analysis.*;

@SuppressWarnings("nls")
public final class TNum extends Token
{
    public TNum()
    {
        super.setText("num");
    }

    public TNum(int line, int pos)
    {
        super.setText("num");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNum(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNum(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNum text.");
    }
}
