/* This file was generated by SableCC (http://www.sablecc.org/). */

package grammar.ini.node;

import grammar.ini.analysis.*;

@SuppressWarnings("nls")
public final class TUpto extends Token
{
    public TUpto()
    {
        super.setText("upto");
    }

    public TUpto(int line, int pos)
    {
        super.setText("upto");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUpto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUpto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUpto text.");
    }
}
